[22-Aug-23 20:17:12 - INFO - web_interface.py:79 - toggle_calibration()]  Starting calibration capture for platform-fc800000.usb-usb-0:1:1.0-video-index0
[22-Aug-23 20:17:12 - INFO - init.py:66 - <module>()]  Beginning calibration
[22-Aug-23 20:17:26 - INFO - calibration.py:90 - processFrame()]  Calibration image saved to Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0CalImgs/1692749846019400547.png
[22-Aug-23 20:17:29 - INFO - calibration.py:90 - processFrame()]  Calibration image saved to Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0CalImgs/1692749849419322929.png
[22-Aug-23 20:17:33 - INFO - calibration.py:90 - processFrame()]  Calibration image saved to Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0CalImgs/1692749853819617819.png
[22-Aug-23 20:17:41 - INFO - calibration.py:90 - processFrame()]  Calibration image saved to Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0CalImgs/1692749861614097250.png
[22-Aug-23 20:17:50 - INFO - web_interface.py:83 - toggle_calibration()]  Stopping calibration capture
[22-Aug-23 20:17:56 - INFO - calibration.py:203 - generateCalibration()]  Calibration successfully generated and saved to ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(1280, 800)CalData.json with resolution (1280, 800)
[22-Aug-23 20:17:56 - INFO - camera.py:115 - setCalibration()]  Calibration set for platform-fc800000.usb-usb-0:1:1.0-video-index0, using [[948.01281265   0.         661.91827916]
 [  0.         977.15966214 415.60070268]
 [  0.           0.           1.        ]]
[[ 0.02142982  0.23721191 -0.02027148  0.06486291  3.40178333 -0.0561533
   0.59251678  3.09135699 -0.06196457  0.00703724  0.02442619 -0.01828851
  -0.04011762  0.13420393]]
[22-Aug-23 20:21:47 - WARNING - web_interface.py:47 - disconnect()]  Client disconnected
[22-Aug-23 20:21:47 - INFO - web_interface.py:42 - connect()]  Client connected
[22-Aug-23 20:22:14 - ERROR - image_streams.py:21 - update()]  Updated image is None - Skipping
[22-Aug-23 20:22:15 - INFO - calibration.py:291 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(160, 120)CalData.json
[22-Aug-23 20:22:15 - ERROR - camera.py:235 - importCalibration()]  Calibration not found for camera platform-fc800000.usb-usb-0:1:1.0-video-index0 at resolution (160, 120)
[22-Aug-23 20:22:15 - INFO - camera.py:152 - setResolution()]  Resolution set to (160, 120) for platform-fc800000.usb-usb-0:1:1.0-video-index0
[22-Aug-23 20:22:44 - ERROR - camera.py:139 - setResolution()]  Failed to set resolution to (176, 144) for platform-fc800000.usb-usb-0:1:1.0-video-index0, using (160, 120)
[22-Aug-23 20:22:51 - ERROR - camera.py:139 - setResolution()]  Failed to set resolution to (416, 240) for platform-fc800000.usb-usb-0:1:1.0-video-index0, using (160, 120)
[22-Aug-23 20:22:55 - ERROR - camera.py:139 - setResolution()]  Failed to set resolution to (800, 448) for platform-fc800000.usb-usb-0:1:1.0-video-index0, using (160, 120)
[22-Aug-23 20:23:01 - ERROR - camera.py:139 - setResolution()]  Failed to set resolution to (1280, 800) for platform-fc800000.usb-usb-0:1:1.0-video-index0, using (160, 120)
[22-Aug-23 20:23:13 - ERROR - camera.py:139 - setResolution()]  Failed to set resolution to (1280, 800) for platform-fc800000.usb-usb-0:1:1.0-video-index0, using (160, 120)
[22-Aug-23 20:23:28 - INFO - init.py:140 - <module>()]  Shutting down
[22-Aug-23 20:23:30 - INFO - init.py:14 - <module>()]  ----------- Starting Up -----------
[22-Aug-23 20:23:30 - INFO - state.py:138 - setIP()]  Attempting to set static IP
[22-Aug-23 20:23:30 - INFO - state.py:149 - setIP()]  Static IP set: 10.27.67.10
[22-Aug-23 20:23:30 - INFO - camera.py:21 - __init__()]  Platform is linux
[22-Aug-23 20:23:30 - INFO - camera.py:36 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[22-Aug-23 20:23:30 - INFO - camera.py:61 - __init__()]  Supported resolutions: [(160, 120), (176, 144), (320, 240), (352, 288), (416, 240), (424, 240), (640, 360), (640, 480), (800, 448), (800, 600), (960, 544), (1280, 720), (1280, 800)]
[22-Aug-23 20:23:30 - INFO - camera.py:67 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[22-Aug-23 20:23:30 - INFO - camera.py:82 - __init__()]  Config found!
[22-Aug-23 20:23:30 - INFO - calibration.py:291 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(160, 120)CalData.json
[22-Aug-23 20:23:30 - ERROR - camera.py:235 - importCalibration()]  Calibration not found for camera platform-fc800000.usb-usb-0:1:1.0-video-index0 at resolution (160, 120)
[22-Aug-23 20:23:30 - INFO - camera.py:152 - setResolution()]  Resolution set to (160, 120) for platform-fc800000.usb-usb-0:1:1.0-video-index0
[22-Aug-23 20:23:30 - INFO - camera.py:166 - setGain()]  Gain set to -1.0
[22-Aug-23 20:23:30 - WARNING - camera.py:184 - setExposure()]  Exposure not set: -1.0 not accepted
[22-Aug-23 20:23:31 - INFO - image_streams.py:45 - __init__()]  Tag layout loaded
[22-Aug-23 20:23:35 - INFO - init.py:44 - <module>()]  Web server ready
[22-Aug-23 20:23:35 - INFO - Processing.py:15 - __init__()]  Tag layout loaded
[22-Aug-23 20:23:35 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[22-Aug-23 20:23:35 - INFO - state.py:105 - makePublisher()]  Robot publisher created: 2767 - WallEye
[22-Aug-23 20:23:35 - INFO - init.py:53 - <module>()]  Starting main loop
[22-Aug-23 20:23:37 - INFO - web_interface.py:42 - connect()]  Client connected
[22-Aug-23 20:23:56 - INFO - camera.py:187 - setExposure()]  Exposure set to 51.0
[22-Aug-23 20:23:58 - WARNING - camera.py:163 - setGain()]  Gain not set: 1.67 not accepted
[22-Aug-23 20:23:59 - WARNING - camera.py:163 - setGain()]  Gain not set: 8.18 not accepted
[22-Aug-23 20:24:04 - ERROR - image_streams.py:21 - update()]  Updated image is None - Skipping
[22-Aug-23 20:24:04 - INFO - calibration.py:291 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(1280, 800)CalData.json
[22-Aug-23 20:24:04 - INFO - camera.py:115 - setCalibration()]  Calibration set for platform-fc800000.usb-usb-0:1:1.0-video-index0, using [[948.01281265   0.         661.91827916]
 [  0.         977.15966214 415.60070268]
 [  0.           0.           1.        ]]
[[ 0.02142982  0.23721191 -0.02027148  0.06486291  3.40178333 -0.0561533
   0.59251678  3.09135699 -0.06196457  0.00703724  0.02442619 -0.01828851
  -0.04011762  0.13420393]]
[22-Aug-23 20:24:04 - INFO - camera.py:152 - setResolution()]  Resolution set to (1280, 800) for platform-fc800000.usb-usb-0:1:1.0-video-index0
[22-Aug-23 20:24:05 - INFO - image_streams.py:25 - update()]  Updated image is NOT none!
